build:
  image: ubuntu:xenial
  environment:
    - http_proxy=$http_proxy
    - DATABASE_URL=postgres://ecs:ecs@localhost:5936/
  commands:
    - chmod +x scripts/*.sh
    - scripts/install-os-deps.sh --no-upgrade
    - scripts/install-user-deps.sh ./env
    - scripts/create-dirs.sh ./
    - . ./env/bin/activate
    - coverage run source='.' manage.py test
    - coverage report --omit=*settings*,*test* --fail-under 50

compose:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=ecs
      - POSTGRES_PASSWORD=ecs

publish:
  coverage:
    labels:
      - coverage
      - reporting
